### ISSUE TITLE
apparently blows up with just-released PhpStorm 2916.2

### ISSUE THREAD

**Issue by narration-sd** [cmazx/yiistorm#41]
Had just started the fresh JetBrains IDE. Also pushed Migrations button newly showing. Maybe  that was yours?  Yii 1 is involved in this project. Yes, that appears to be the point -- restarted PhpStorm and got the stack trace again.

class com.yiistorm.elements.MigrationsToolWindow$1$1 overrides final method cancel.()V
java.lang.VerifyError: class com.yiistorm.elements.MigrationsToolWindow$1$1 overrides final method cancel.()V
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:268)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:264)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:233)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:119)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:73)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:62)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.yiistorm.elements.MigrationsToolWindow$1.run(MigrationsToolWindow.java:223)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by cmazx** [comment]
on wich OS?

**Comment by cmazx** [comment]
Eh, do you install plugin from repository?

**Comment by cmazx** [comment]
I will fix this, as soon as i can

**Comment by ivan-pomortsev** [comment]
Actually there is a lot of extensions which are crashed after this update so I still didn't do it and I think I will not ;) (I found it on colleagues IDEs)

**Comment by narration-sd** [comment]
Thanks, Mazx - appreciate to hear.

An additional clue is that I started PhpStorm this evening, and did _not_ push the unusual new Migrations button. The same stack trace occurred a moment after starting, so I think that is the actual instigator.

Just a quick look at the trace seems to suggest JetBrains may have newly declared a cancel method final which you want to override -- it's been a long time since I did Java, but this is kind of generic. So it may be their fault, but talking to them ought to turn up a middle way, one that works for both.

Best fortune  on it,
Clive
