### ISSUE TITLE
Будет обновление?

### ISSUE THREAD

**Issue by b1rdex** [cmazx/yiistorm#43]
В текущем EAP постоянно крэшится. Смысл логи скидывать вообще есть или проект заброшен?

**Comment by b1rdex** [comment]
```
org/apache/tools/ant/DirectoryScanner
java.lang.NoClassDefFoundError: org/apache/tools/ant/DirectoryScanner
    at com.yiistorm.helpers.CompleterHelper.searchFiles(CompleterHelper.java:15)
    at com.yiistorm.completition.providers.ViewCompletionProvider.addCompletions(ViewCompletionProvider.java:157)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
    at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
    at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:772)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:90)
    at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:754)
    at com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:87)
    at com.intellij.codeInsight.completion.AsyncCompletion$$Lambda$1382/704800916.run(Unknown Source)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:873)
    at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:84)
    at com.intellij.codeInsight.completion.AsyncCompletion$$Lambda$1381/1337933088.run(Unknown Source)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:82)
    at com.intellij.codeInsight.completion.AsyncCompletion$$Lambda$1380/777640232.run(Unknown Source)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

При ctrl+space на имени шаблона в render() из view виджета.

**Comment by cmazx** [comment]
спасибо за инфу
